import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useState, useEffect } from "react";
import Layout from "../components/Layout/Layout";
import genderSelectMan from "../assets/images/genderSelectMan.jpg";
import genderSelectWoman from "../assets/images/genderSelectWoman.jpg";
import bgCard from "../assets/images/bgCard.png";

type Props = {};

function calc({}: Props) {
  const [gender, setGender] = useState<String>("Woman");

  const genderSelected = () => {
    const getGender = document.getElementById("genderSelect");
    const getNextLocation = document.getElementsByClassName("2");
    setGender(getGender.value);
  };

  const Bgpicture = () => {
    if (gender == "Woman") {
      return genderSelectWoman;
    } else {
      return genderSelectMan;
    }
  };

  useEffect(() => {
    console.log(gender);
  }, [gender]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className="h-screen w-screen flex flex-col items-center justify-center gap-10">
          <h2>hello world</h2>
          <section className=" w-full h-3/4 overflow-x-auto snap-x snap-mandatory scroll-smooth scrollbar-none flex gap-x-5 p-12 ">
            <form className=" w-full flex items-center  gap-5" method="Post">
              {/**premier conteneur  en faire des compo séparé pour meilleur opti du code*/}
              <div
                className=" relative w-full min-w-full h-full border-4 border-green-500 rounded-md snap-center flex flex-col items-center justify-center gap-10"
                id="1"
              >
                <Image
                  src={bgCard}
                  alt={"genre selectionné"}
                  className=" object-cover object-top w-full h-full absolute z-0"
                />
                <h3 className="text-4xl z-10 text-white bg-green-500 p-4 rounded-md">
                  vous êtes:
                </h3>
                <select
                  id="genderSelect"
                  onChange={() => genderSelected()}
                  className="z-10 w-3/4 max-w-xl"
                >
                  <option value="Woman">Une Femme</option>
                  <option value="Man">Un Homme</option>
                </select>
                <div className=" relative w-48 h-48 rounded-full border-2 border-green-500">
                  <Image src={Bgpicture()} alt={''} className='absolute rounded-full object-cover h-full w-full' />
                </div>
                <Link
                  id="1"
                  href="#2"
                  className="z-10 w-full flex items-center justify-center"
                >
                  <button className="text-white bg-green-500 p-2 rounded-md w-2/4 max-w-lg">
                    valider
                  </button>
                </Link>
              </div>

              {/**deuxième conteneur */}
              <div
                className="w-full min-w-full h-full border-4 border-green-500 rounded-md snap-center"
                id="2"
              >
                <Link href="#1">
                  <button className="border-4 p-4">previous</button>
                </Link>
              </div>
              {/**deuxième conteneur */}
              <div
                className="w-full min-w-full h-full border-4 border-green-500 rounded-md snap-center"
                id="2"
              >
                <Link href="#1">
                  <button className="border-4 p-4">previous</button>
                </Link>
              </div>
            </form>
          </section>
        </main>
      </Layout>
    </>
  );
}

export default calc;
