import Head from "next/head";
import Image from "next/image";
import runningWoman from '../assets/images/runningwoman.jpg'
import Link from "next/link";
import Layout from "../components/Layout/Layout";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className=" h-screen w-screen snap-y snap-mandatory overflow-y-auto scroll-smooth">

        
          <section className=" h-screen w-full snap-center flex flex-col justify-around items-center">

            <Image src={runningWoman} alt={'femme faisant son jogging'} className='object-cover absolute h-screen' />
 
            <div className="flex flex-col justify-center items-center p-12 gap-10 z-10">
              <h1 className="text-4xl uppercase tracking-[10px] text-white bg-green-500 p-4 pr-2 rounded-md">FiFit</h1>
              <p className="text-2xl text-center text-white bg-green-500 p-2 rounded-md">
                Des repas équilibrés associé à un coaching sportif adapté à vos
                objectifs
              </p>
            </div>

            <div className=" grid grid-cols-2 gap-4 place-items-center md:grid-cols-4 z-10">
              <Link href="calc">
                <div className=" w-40 h-40 border-4 border-green-500 rounded-md bg-neutral-200 drop-shadow-xl hover:scale-110 transition duration-300 active:scale-90 flex flex-col items-center justify-evenly">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-1/2 h-1/2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15.75 15.75V18m-7.5-6.75h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V13.5zm0 2.25h.008v.008H8.25v-.008zm0 2.25h.008v.008H8.25V18zm2.498-6.75h.007v.008h-.007v-.008zm0 2.25h.007v.008h-.007V13.5zm0 2.25h.007v.008h-.007v-.008zm0 2.25h.007v.008h-.007V18zm2.504-6.75h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V13.5zm0 2.25h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V18zm2.498-6.75h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V13.5zM8.25 6h7.5v2.25h-7.5V6zM12 2.25c-1.892 0-3.758.11-5.593.322C5.307 2.7 4.5 3.65 4.5 4.757V19.5a2.25 2.25 0 002.25 2.25h10.5a2.25 2.25 0 002.25-2.25V4.757c0-1.108-.806-2.057-1.907-2.185A48.507 48.507 0 0012 2.25z"
                    />
                  </svg>
                  <h2 className="text-center">Calculette <br /> IMC</h2>
                </div>
              </Link>
              <Link href="dashboard">
                <div className=" w-40 h-40 border-4 border-green-500 rounded-md bg-neutral-200 drop-shadow-xl hover:scale-110 transition duration-300 active:scale-90 flex flex-col items-center justify-evenly">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-1/2 h-1/2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M3.75 3v11.25A2.25 2.25 0 006 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0118 16.5h-2.25m-7.5 0h7.5m-7.5 0l-1 3m8.5-3l1 3m0 0l.5 1.5m-.5-1.5h-9.5m0 0l-.5 1.5m.75-9l3-3 2.148 2.148A12.061 12.061 0 0116.5 7.605"
                    />
                  </svg>
                  <h2 className="text-center">Tableau de bord </h2>
                </div>
              </Link>
              <Link href='chat'>
              <div className=" w-40 h-40 border-4 border-green-500 rounded-md bg-neutral-200 drop-shadow-xl hover:scale-110 transition duration-300 active:scale-90 flex flex-col items-center justify-evenly">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-1/2 h-1/2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M8.625 9.75a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H8.25m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0H12m4.125 0a.375.375 0 11-.75 0 .375.375 0 01.75 0zm0 0h-.375m-13.5 3.01c0 1.6 1.123 2.994 2.707 3.227 1.087.16 2.185.283 3.293.369V21l4.184-4.183a1.14 1.14 0 01.778-.332 48.294 48.294 0 005.83-.498c1.585-.233 2.708-1.626 2.708-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z"
                    />
                  </svg>
                  <h2 className="text-center">Contacter un pro</h2>
                </div>
              </Link>
              <Link href="random">
                <div className=" w-40 h-40 border-4 border-green-500 rounded-md bg-neutral-200 drop-shadow-xl hover:scale-110 transition duration-300 active:scale-90 flex flex-col items-center justify-evenly">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth={1.5}
                    stroke="currentColor"
                    className="w-1/2 h-1/2"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z"
                    />
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M12 18a3.75 3.75 0 00.495-7.467 5.99 5.99 0 00-1.925 3.546 5.974 5.974 0 01-2.133-1A3.75 3.75 0 0012 18z"
                    />
                  </svg>
                  <h2 className="text-center">Cours aléatoire</h2>
                </div>
              </Link>
            </div>
          </section>
        </main>
      </Layout>
    </>
  );
}
